services:
  frontend:
    image: exowebapp
    depends_on:
      - mariadb
    ports:
      - "8080:80"

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=test
    volumes:
      - mariadb:/var/lib/mysql

  exodbweb: 
    image: exodbweb
    depends_on:
      - mariadb
    ports:
      - "8081:8081"
    environment:
      - MARIADB_ADDR=mariadb

volumes:
  mariadb:
    name: "exodb"
